package com.stage.coc.enums;

public enum CategorieMarchandise {
    PRODUITS_INDUSTRIELS_ET_TECHNIQUES,
    VEHICULES_ET_PIECES_DETACHEES,
    EQUIPEMENTS_ECLAIRAGE,
    JOUETS_ET_ARTICLES_ENFANTS,
    MATERIEL_ELECTRIQUE_ET_CABLAGE,
    MEUBLES_ET_ARTICLES_BOIS,
    PRODUITS_AGROALIMENTAIRES,
    PRODUITS_PHARMACEUTIQUES_ET_COSMETIQUES,
    TEXTILE_ET_HABILLEMENT,
    EQUIPEMENTS_INFORMATIQUES_ET_TELECOMMUNICATION,
    PRODUITS_CHIMIQUES,
    EMBALLAGES_ET_PRODUITS_PLASTIQUE,
    PRODUITS_PETROLIERS_ET_LUBRIFIANTS,
    PRODUITS_CULTURELS_ET_EDUCATIFS,
    PRODUITS_AGRICOLES_ANIMAUX_VIVANTS
}